### ISSUE TITLE
does it support Ant like "exclude" pattern?

### ISSUE THREAD

**Issue by linsea** [EsotericSoftware/wildcard#11]
does it support Ant like "exclude" pattern?
or like this gradle style : https://docs.gradle.org/3.3/javadoc/org/gradle/api/file/CopySpec.html

**Comment by NathanSweet** [comment]
This is an issue track. Please use the mailing list for questions.
https://groups.google.com/forum/#!topic/wildcard-users/90nTPDalk2I
