### ISSUE TITLE
When matching on Windows, incorrect paths are returned

### ISSUE THREAD

**Issue by grzegorzgoldapl** [EsotericSoftware/wildcard#12]
I'm using pattern like C:\nuke\** (or C:/nuke/** - it doesn't matter, the bug still happens).

When running on Windows, I iterate through paths and if there is only top level, like in pattern above, I get incorrect paths where the first letter of top-level directory:

C:/uke/CustomMergeBlue.gizmo
C:/uke/CustomGizmo.gizmo

etc.

If it's C:/nuke/plugins/**, the paths are correct, i.e. the top-level directory doesn't have first letter removed.

**Comment by NathanSweet** [comment]
Please provide code that shows the problem and I'll reopen the issue. Eg:
```
System.out.println(new Paths().glob("C:\\", "nuke**"));
```

**Comment by grzegorzgoldapl** [comment]
I'm sorry - I see it's fixed, I had older version of the library.
